name: flrsh-dev/cran-checks/check-pkg
description: |
  Check your CRAN package for failing CRAN checks. If the package does not exist on CRAN, the check will fail. If your package has the status NOTE or OK for all check flavors, then the test passes.
author: 'Josiah Parry'


inputs:
  pkg:
    description: |
      The package to check as a scalar character.
    required: true


runs:
  using: "composite"
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install yyjsonr
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::yyjsonr

    - name: Check CRAN checks
      id: cran-check-status
      run: |
        pkgs <- unlist(strsplit("${{ inputs.pkg }}", "\\s+"))
        pkgs <- pkgs[pkgs != ""]
        
        pkg_miss <- character(0)
        pkg_errs <- character(0)
        pkg_warn <- character(0)
        for(pkg in pkgs) {
          fp <- paste0("https://flrsh-dev.github.io/cran-checks/", pkg, ".json")
        
          json <- tryCatch(readLines(fp),
                           warning = function(e) {
                             return(NULL)
                           }
          )
          if(is.null(json)) {
            pkg_miss <- c(pkg_miss, pkg)
            next
          }
        
          res <- yyjsonr::read_json_str(json)
        
          if (any("ERROR" %in% res$results[[1]]$check_status)) {
            pkg_errs <- c(pkg_errs, pkg)
          } else if (any("WARN" %in% res$results[[1]]$check_status)) {
            pkg_warn <- c(pkg_warn, pkg)
          }
        }
        
        msg <- ""
        if(length(pkg_miss) > 0) {
          msg <- paste0("Cannot find ", paste0("{", pkg_miss, "}", collapse = ", "), " on CRAN. ")
        }
        if(length(pkg_errs) > 0) {
          msg <- paste0(msg, "Errors found in CRAN checks for ", paste0("{", pkg_errs, "}", collapse = ", "), ". ")
        }
        if(length(pkg_warn) > 0) {
          msg <- paste0(msg, "Warnings found in CRAN checks for ", paste0("{", pkg_warn, "}", collapse = ", "), ".")
        }
        if(nchar(msg) > 0) {
          msg <- paste0(msg, "\n\nReview logs at:\n", paste0("  https://cran.r-project.org/web/checks/check_results_", c(pkg_errs, pkg_warn), ".html", collapse = "\n"))
          stop(msg)
        }
        
        message("\u2713 No warnings or errors for ", paste0("{", pkgs, "}", collapse = ", "), ".")
      shell: Rscript {0}
