name: flrsh-dev/cran-checks/check-pkg
description: |
  Check your CRAN package for failing CRAN checks. If the package does not exist on CRAN, the check will fail. If your package has the status NOTE or OK for all check flavors, then the test passes.
author: 'Josiah Parry'


inputs:
  pkg:
    description: |
      The package to check as a scalar character.
    required: true


runs:
  using: "composite"
  steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install yyjsonr
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::yyjsonr

    - name: Check CRAN checks
      id: cran-check-status
      run: |
        pkg <- "${{ inputs.pkg }}"
        fp <- paste0("https://flrsh-dev.github.io/cran-checks/", pkg, ".json")

        json <- tryCatch(readLines(fp),
          warning = function(e) {
            stop("Package ", pkg, " not found in CRAN checks", call. = FALSE)
          }
        )

        res <- yyjsonr::read_json_str(json)
        
        if (any("ERROR" %in% res$results[[1]]$check_status)) {
          stop(
            "Errors found in CRAN checks",
            "\n",
            "Review logs at ", 
            "https://cran.r-project.org/web/checks/check_results_", pkg, ".html"
          )
        } else if (any("WARN" %in% res$results[[1]]$check_status)) {
          stop(
            "Warnings found in CRAN checks",
            "\n",
            "Review logs at ", 
            "https://cran.r-project.org/web/checks/check_results_", pkg, ".html"
          )
        }
        
        message("\u2713 `", pkg, "` has no warnings or errors")
      shell: Rscript {0}
